name: task 
on: push 
jobs: 
 my-job:
   runs-on: ubuntu-latest 
   steps: 
   - name: my-steps 
     run: echo "hello world"

 my-job2:
   runs-on: ubuntu-latest 
   steps: 
   - name: my-steps 
     run: echo "hello world again"
